apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: "Endring i arbeidstakers behandlende enhet"
    dcat.data.nav.no/description: >-
      Topic inneholder oppdateringer på endringer i arbeidstakers behandlende enhet
  name: behandlendeenhet
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  pool: {{ kafkaPool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: teamsykefravr
      application: syfobehandlendeenhet
      access: write
    - team: teamsykefravr
      application: syfooversiktsrv
      access: read
