apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfobehandlendeenhet
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
    - "https://syfobehandlendeenhet.nais.adeo.no"
  vault:
    enabled: true
  env:
    - name: APP_NAME
      value: "syfobehandlendeenhet"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_DISCOVERYURL
      value: http://security-token-service/rest/v1/sts/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_ACCEPTEDAUDIENCE
      value: srvispersonoppgave,srvsyfooversikthen,srvsyfomotebehov,srvsyfomoteadmin,srvsyfooversiktsrv,srvsyfooppfolgings,srvsyfo-tilgangsko
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_DISCOVERYURL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_ACCEPTEDAUDIENCE
      value: 9b4e07a3-4f4c-4bab-b866-87f62dff480d
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: PERSON_V3_URL
      value: https://wasapp.adeo.no/tpsws/ws/Person/v3
    - name: NORG2_URL
      value: https://app.adeo.no/norg2/api/v1
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.adeo.no/syfo-tilgangskontroll/api/tilgang
