apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfobehandlendeenhet
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://syfobehandlendeenhet.intern.dev.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: dev-fss
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: dev-gcp
        - application: syfooversiktsrv
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: dev-gcp
    outbound:
      external:
        - host: "norg2.prod-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
      rules:
        - application: syfobehandlendeenhet-redis
        - application: istilgangskontroll
        - application: skjermede-personer-pip
          namespace: nom
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: syfobehandlendeenhet-db
        diskAutoresize: true
  envFrom:
    - secret: syfobehandlendeenhet-redis-password
  kafka:
    pool: nav-dev
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: KTOR_ENV
      value: "production"
    - name: NORG2_URL
      value: "https://norg2.dev-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: REDIS_HOST
      value: "syfobehandlendeenhet-redis.teamsykefravr.svc.cluster.local"
    - name: SKJERMEDEPERSONERPIP_CLIENT_ID
      value: "dev-gcp.nom.skjermede-personer-pip"
    - name: SKJERMEDEPERSONERPIP_URL
      value: "http://skjermede-personer-pip.nom"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
