apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfobehandlendeenhet
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
    - "https://syfobehandlendeenhet.intern.nav.no"
    - "https://syfobehandlendeenhet.prod-fss-pub.nais.io"
    - "https://syfobehandlendeenhet.nais.adeo.no"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: ispersonoppgave
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomoteadmin
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomotebehov
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfooversikthendelsetilfelle
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfo-tilgangskontroll
          namespace: teamsykefravr
          cluster: prod-fss
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://syfobehandlendeenhet.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/kv/prod/fss/syfobehandlendeenhet/default"
        mountPath: "/secrets/vault"
  env:
    - name: APP_NAME
      value: "syfobehandlendeenhet"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_DISCOVERYURL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_ACCEPTEDAUDIENCE
      value: srvispersonoppgave,srvsyfooversikthen,srvsyfomotebehov,srvsyfomoteadmin,srvsyfooppfolgings
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.intern.nav.no/graphql"
    - name: NORG2_URL
      value: https://app.adeo.no/norg2/api/v1
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.adeo.no/syfo-tilgangskontroll/api/tilgang
