apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfobehandlendeenhet
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
    - "https://syfobehandlendeenhet.dev.intern.nav.no"
    - "https://syfobehandlendeenhet.dev-fss-pub.nais.io"
    - "https://syfobehandlendeenhet.nais.preprod.local"
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/dev/srvsyfobehandlendeenhet"
        mountPath: "/secrets/serviceuser/syfobehandlendeenhet"
      - kvPath: "/kv/preprod/fss/syfobehandlendeenhet/default"
        mountPath: "/secrets/vault"
  env:
    - name: APP_NAME
      value: "syfobehandlendeenhet"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_DISCOVERYURL
      value: http://security-token-service/rest/v1/sts/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_ACCEPTEDAUDIENCE
      value: srvispersonoppgave,srvsyfooversikthen,srvsyfomotebehov,srvsyfomoteadmin,srvsyfooversiktsrv,srvsyfooppfolgings,srvsyfo-tilgangsko
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_DISCOVERYURL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_ACCEPTEDAUDIENCE
      value: 38e07d31-659d-4595-939a-f18dce3446c5
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.preprod.local
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: NORG2_URL
      value: https://app-q1.adeo.no/norg2/api/v1
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll/api/tilgang
