apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfobehandlendeenhet
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://syfobehandlendeenhet.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: ispersonoppgave
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfomoteadmin
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: dev-fss
        - application: syfooversikthendelsetilfelle
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfooversiktsrv
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfo-tilgangskontroll
          namespace: teamsykefravr
          cluster: dev-fss
    outbound:
      external:
        - host: "isproxy.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "skjermede-personer-pip.dev.intern.nav.no"
        - host: "syfo-tilgangskontroll.dev-fss-pub.nais.io"
      rules:
        - application: syfobehandlendeenhet-redis
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: syfobehandlendeenhet-redis-password
  env:
    - name: ISPROXY_CLIENT_ID
      value: "dev-fss.teamsykefravr.isproxy"
    - name: ISPROXY_URL
      value: "https://isproxy.dev-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: REDIS_HOST
      value: "syfobehandlendeenhet-redis.teamsykefravr.svc.cluster.local"
    - name: SKJERMEDEPERSONERPIP_CLIENT_ID
      value: "dev-gcp.nom.skjermede-personer-pip"
    - name: SKJERMEDEPERSONERPIP_URL
      value: "https://skjermede-personer-pip.dev.intern.nav.no"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.dev-fss-pub.nais.io"
