apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfobehandlendeenhet
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://syfobehandlendeenhet.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: prod-fss
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: prod-gcp
        - application: syfooversiktsrv
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: meroppfolging-backend
          namespace: team-esyfo
    outbound:
      external:
        - host: "pdl-api.prod-fss-pub.nais.io"
      rules:
        - application: istilgangskontroll
        - application: skjermede-personer-pip
          namespace: nom
        - application: norg2
          namespace: org
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  redis:
    - instance: cache
      access: readwrite
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-f1-micro
        databases:
          - name: syfobehandlendeenhet-db
        diskAutoresize: true
  kafka:
    pool: nav-prod
  env:
    - name: KTOR_ENV
      value: "production"
    - name: NORG2_URL
      value: "http://norg2.org"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: SKJERMEDEPERSONERPIP_CLIENT_ID
      value: "prod-gcp.nom.skjermede-personer-pip"
    - name: SKJERMEDEPERSONERPIP_URL
      value: "http://skjermede-personer-pip.nom"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
