logging.config: classpath:logback-spring.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

no.nav.security.jwt:
  issuers: sts
  issuer:
    sts:
      discoveryurl: <syfonais>
      accepted_audience: <syfonais>
    veileder:
      discoveryurl: <syfonais>
      accepted_audience: <syfonais>
      cookie_name: isso-idtoken
    veilederaad:
      discoveryurl: ${azure.app.well.known.url}
      accepted_audience: ${azure.app.client.id}
      cookiename: ID_token

spring:
  cache.type: redis
  redis:
    host: syfobehandlendeenhet-redis
    port: 6379
  main.banner-mode: 'off'
  jta.atomikos.datasource:
    max-pool-size: 32
    min-pool-size: 8

dev: false
